/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.tax.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.tax.model.ShopBasket;
import com.liferay.tax.model.ShopBasketModel;
import com.liferay.tax.model.ShopBasketSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ShopBasket service. Represents a row in the &quot;jb_ShopBasket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ShopBasketModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShopBasketImpl}.
 * </p>
 *
 * @author jbaeza
 * @see ShopBasketImpl
 * @generated
 */
@JSON(strict = true)
public class ShopBasketModelImpl
	extends BaseModelImpl<ShopBasket> implements ShopBasketModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a shop basket model instance should use the <code>ShopBasket</code> interface instead.
	 */
	public static final String TABLE_NAME = "jb_ShopBasket";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"shopBasketId", Types.BIGINT},
		{"active_", Types.BOOLEAN}, {"createDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("shopBasketId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table jb_ShopBasket (uuid_ VARCHAR(75) null,shopBasketId LONG not null primary key,active_ BOOLEAN,createDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table jb_ShopBasket";

	public static final String ORDER_BY_JPQL =
		" ORDER BY shopBasket.shopBasketId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY jb_ShopBasket.shopBasketId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long UUID_COLUMN_BITMASK = 1L;

	public static final long SHOPBASKETID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ShopBasket toModel(ShopBasketSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ShopBasket model = new ShopBasketImpl();

		model.setUuid(soapModel.getUuid());
		model.setShopBasketId(soapModel.getShopBasketId());
		model.setActive(soapModel.isActive());
		model.setCreateDate(soapModel.getCreateDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ShopBasket> toModels(ShopBasketSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ShopBasket> models = new ArrayList<ShopBasket>(soapModels.length);

		for (ShopBasketSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public ShopBasketModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _shopBasketId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setShopBasketId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _shopBasketId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ShopBasket.class;
	}

	@Override
	public String getModelClassName() {
		return ShopBasket.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ShopBasket, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ShopBasket, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ShopBasket, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((ShopBasket)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ShopBasket, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ShopBasket, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ShopBasket)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ShopBasket, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ShopBasket, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ShopBasket>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ShopBasket.class.getClassLoader(), ShopBasket.class,
			ModelWrapper.class);

		try {
			Constructor<ShopBasket> constructor =
				(Constructor<ShopBasket>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<ShopBasket, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ShopBasket, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ShopBasket, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ShopBasket, Object>>();
		Map<String, BiConsumer<ShopBasket, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ShopBasket, ?>>();

		attributeGetterFunctions.put("uuid", ShopBasket::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<ShopBasket, String>)ShopBasket::setUuid);
		attributeGetterFunctions.put(
			"shopBasketId", ShopBasket::getShopBasketId);
		attributeSetterBiConsumers.put(
			"shopBasketId",
			(BiConsumer<ShopBasket, Long>)ShopBasket::setShopBasketId);
		attributeGetterFunctions.put("active", ShopBasket::getActive);
		attributeSetterBiConsumers.put(
			"active", (BiConsumer<ShopBasket, Boolean>)ShopBasket::setActive);
		attributeGetterFunctions.put("createDate", ShopBasket::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<ShopBasket, Date>)ShopBasket::setCreateDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getShopBasketId() {
		return _shopBasketId;
	}

	@Override
	public void setShopBasketId(long shopBasketId) {
		_shopBasketId = shopBasketId;
	}

	@JSON
	@Override
	public boolean getActive() {
		return _active;
	}

	@JSON
	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ShopBasket.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ShopBasket toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ShopBasket>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ShopBasketImpl shopBasketImpl = new ShopBasketImpl();

		shopBasketImpl.setUuid(getUuid());
		shopBasketImpl.setShopBasketId(getShopBasketId());
		shopBasketImpl.setActive(isActive());
		shopBasketImpl.setCreateDate(getCreateDate());

		shopBasketImpl.resetOriginalValues();

		return shopBasketImpl;
	}

	@Override
	public int compareTo(ShopBasket shopBasket) {
		long primaryKey = shopBasket.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ShopBasket)) {
			return false;
		}

		ShopBasket shopBasket = (ShopBasket)object;

		long primaryKey = shopBasket.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ShopBasket> toCacheModel() {
		ShopBasketCacheModel shopBasketCacheModel = new ShopBasketCacheModel();

		shopBasketCacheModel.uuid = getUuid();

		String uuid = shopBasketCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			shopBasketCacheModel.uuid = null;
		}

		shopBasketCacheModel.shopBasketId = getShopBasketId();

		shopBasketCacheModel.active = isActive();

		Date createDate = getCreateDate();

		if (createDate != null) {
			shopBasketCacheModel.createDate = createDate.getTime();
		}
		else {
			shopBasketCacheModel.createDate = Long.MIN_VALUE;
		}

		return shopBasketCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ShopBasket, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ShopBasket, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ShopBasket, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ShopBasket)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ShopBasket, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ShopBasket, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ShopBasket, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ShopBasket)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ShopBasket>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _shopBasketId;
	private boolean _active;
	private Date _createDate;
	private long _columnBitmask;
	private ShopBasket _escapedModel;

}