/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.tax.model.impl;

import com.liferay.tax.model.ShopBasket;
import com.liferay.tax.service.ShopBasketLocalServiceUtil;

/**
 * The extended model base implementation for the ShopBasket service. Represents a row in the &quot;jb_ShopBasket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ShopBasketImpl}.
 * </p>
 *
 * @author jbaeza
 * @see ShopBasketImpl
 * @see ShopBasket
 * @generated
 */
public abstract class ShopBasketBaseImpl
	extends ShopBasketModelImpl implements ShopBasket {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a shop basket model instance should use the <code>ShopBasket</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ShopBasketLocalServiceUtil.addShopBasket(this);
		}
		else {
			ShopBasketLocalServiceUtil.updateShopBasket(this);
		}
	}

}