/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.tax.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ShopBasket service. Represents a row in the &quot;jb_ShopBasket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.tax.model.impl.ShopBasketModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.tax.model.impl.ShopBasketImpl</code>.
 * </p>
 *
 * @author jbaeza
 * @see ShopBasket
 * @generated
 */
@ProviderType
public interface ShopBasketModel extends BaseModel<ShopBasket> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a shop basket model instance should use the {@link ShopBasket} interface instead.
	 */

	/**
	 * Returns the primary key of this shop basket.
	 *
	 * @return the primary key of this shop basket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this shop basket.
	 *
	 * @param primaryKey the primary key of this shop basket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this shop basket.
	 *
	 * @return the uuid of this shop basket
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this shop basket.
	 *
	 * @param uuid the uuid of this shop basket
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the shop basket ID of this shop basket.
	 *
	 * @return the shop basket ID of this shop basket
	 */
	public long getShopBasketId();

	/**
	 * Sets the shop basket ID of this shop basket.
	 *
	 * @param shopBasketId the shop basket ID of this shop basket
	 */
	public void setShopBasketId(long shopBasketId);

	/**
	 * Returns the active of this shop basket.
	 *
	 * @return the active of this shop basket
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this shop basket is active.
	 *
	 * @return <code>true</code> if this shop basket is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this shop basket is active.
	 *
	 * @param active the active of this shop basket
	 */
	public void setActive(boolean active);

	/**
	 * Returns the create date of this shop basket.
	 *
	 * @return the create date of this shop basket
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this shop basket.
	 *
	 * @param createDate the create date of this shop basket
	 */
	public void setCreateDate(Date createDate);

}